// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>ActivityPosEventLogger</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace ActivityPosEventLogger
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class PosEvent
    {

        private string dateField;

        private long terminalField;

        private string eventNameField;

        private string specialMessageField;

        private PosEventEmployee employeeField;

        private PosEventItem itemField;

        private PosEventPayment paymentField;

        private PosEventComp compField;

        private PosEventPromo promoField;

        public PosEvent()
        {
            this.promoField = new PosEventPromo();
            this.compField = new PosEventComp();
            this.paymentField = new PosEventPayment();
            this.itemField = new PosEventItem();
            this.employeeField = new PosEventEmployee();
        }

        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        public long Terminal
        {
            get
            {
                return this.terminalField;
            }
            set
            {
                this.terminalField = value;
            }
        }

        public string EventName
        {
            get
            {
                return this.eventNameField;
            }
            set
            {
                this.eventNameField = value;
            }
        }

        public string SpecialMessage
        {
            get
            {
                return this.specialMessageField;
            }
            set
            {
                this.specialMessageField = value;
            }
        }

        public PosEventEmployee Employee
        {
            get
            {
                return this.employeeField;
            }
            set
            {
                this.employeeField = value;
            }
        }

        public PosEventItem Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        public PosEventPayment Payment
        {
            get
            {
                return this.paymentField;
            }
            set
            {
                this.paymentField = value;
            }
        }

        public PosEventComp Comp
        {
            get
            {
                return this.compField;
            }
            set
            {
                this.compField = value;
            }
        }

        public PosEventPromo Promo
        {
            get
            {
                return this.promoField;
            }
            set
            {
                this.promoField = value;
            }
        }
    }

    public partial class PosEventEmployee
    {

        private long idField;

        private string firstNameField;

        private string lastNameField;

        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }

    public partial class PosEventItem
    {

        private long idField;

        private string nameField;

        private double priceField;

        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }

    public partial class PosEventPayment
    {

        private string paymentMethodField;

        private double amountField;

        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }

        public double Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    public partial class PosEventComp
    {

        private string compDescField;

        private long compTypeIdField;

        public string CompDesc
        {
            get
            {
                return this.compDescField;
            }
            set
            {
                this.compDescField = value;
            }
        }

        public long CompTypeId
        {
            get
            {
                return this.compTypeIdField;
            }
            set
            {
                this.compTypeIdField = value;
            }
        }
    }

    public partial class PosEventPromo
    {

        private string promoDescField;

        private long promotionIdField;

        public string PromoDesc
        {
            get
            {
                return this.promoDescField;
            }
            set
            {
                this.promoDescField = value;
            }
        }

        public long PromotionId
        {
            get
            {
                return this.promotionIdField;
            }
            set
            {
                this.promotionIdField = value;
            }
        }
    }
}
